sudo: false
language: bash
dist: bionic

script:
  - echo -e "Host $VPS_HOST\n\tStrictHostKeyChecking no\n" >>~/.ssh/config
  - echo $VPS_KEY | base64 --decode >~/.ssh/travis_rsa
  - chmod 600 ~/.ssh/travis_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/travis_rsa
  - ssh -i ~/.ssh/travis_rsa -o UserKnownHostsFile=/dev/null $VPS_USERNAME@$VPS_HOST "docker version && docker-compose version"
  - ssh -i ~/.ssh/travis_rsa -o UserKnownHostsFile=/dev/null $VPS_USERNAME@$VPS_HOST "rm -rf givehost && mkdir -p givehost"
  - scp -r $(pwd)/* $VPS_USERNAME@$VPS_HOST:/root/givehost
#  - docker stop $(docker ps -q)
#  - docker rm $(docker ps -a -q)
#  - docker rmi $(docker images -q)