sudo: false
language: bash
dist: bionic

script:
  - echo -e "Host $VPS_HOST\n\tStrictHostKeyChecking no\n" >>~/.ssh/config
  - echo $VPS_KEY | base64 --decode >~/.ssh/travis_rsa
  - chmod 600 ~/.ssh/travis_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/travis_rsa
  - ls $TRAVIS_BUILD_DIR
  - ssh -i ~/.ssh/travis_rsa -o UserKnownHostsFile=/dev/null $VPS_USERNAME@$VPS_HOST "docker version && docker-compose version"
  - ssh -i ~/.ssh/travis_rsa -o UserKnownHostsFile=/dev/null $VPS_USERNAME@$VPS_HOST "rm -rf givehost && mkdir -p givehost"
  - scp -r $TRAVIS_BUILD_DIR/* $VPS_USERNAME@$VPS_HOST:/root/givehost
  # app config
  - echo "SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/${DATABASE_NAME}" > appenv
  - echo "SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}" >> appenv
  - echo "SPRING_DATASOURCE_PASSWORD==${DATABASE_PASSWORD}" >> appenv
  - echo "SPRING_JPA_HIBERNATE_DDL_AUTO=update" >> appenv
  # db config
  - echo "POSTGRES_PASSWORD=${DATABASE_PASSWORD}" > dbenv
  - echo "POSTGRES_USER=${DATABASE_USERNAME}" > dbenv
  - echo "POSTGRES_DB=${DATABASE_NAME}" > dbenv

  #- ssh -i ~/.ssh/travis_rsa $VPS_USERNAME@$VPS_HOST "docker stop $(docker ps -aq)"
  #- ssh -i ~/.ssh/travis_rsa $VPS_USERNAME@$VPS_HOST "docker rm $(docker ps -aq)"
  #- ssh -i ~/.ssh/travis_rsa $VPS_USERNAME@$VPS_HOST "docker rmi $(docker images -qa)"

  - ssh -i ~/.ssh/travis_rsa $VPS_USERNAME@$VPS_HOST "docker ps --all"
  - ssh -i ~/.ssh/travis_rsa $VPS_USERNAME@$VPS_HOST "ls givehost"
  - ssh -i ~/.ssh/travis_rsa $VPS_USERNAME@$VPS_HOST "printenv"

  - scp appenv $VPS_USERNAME@$VPS_HOST:.givehost/app.env
  - scp dbenv $VPS_USERNAME@$VPS_HOST:.givehost/db.env

  - ssh -i ~/.ssh/travis_rsa $VPS_USERNAME@$VPS_HOST "cd /root/givehost && docker-compose up --detach --build"
