version: "3.9"
services:
  give-host:
    restart: always
    image: kalpak44/give-host:latest
    container_name: give-host
    ports:
      - "8080:8080"
    environment:
      PAYMENTS_STRIPE_KEY_PUBLIC: ${PAYMENTS_STRIPE_KEY_PUBLIC}
      PAYMENTS_STRIPE_KEY_SECRET: ${PAYMENTS_STRIPE_KEY_SECRET}