version: "3.9"
services:
  web:
    restart: on-failure
    build: .
    container_name: give-host
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    env_file:
      - app.env
  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5