version: "3.9"
services:
  web:
    restart: on-failure
    build: .
    container_name: give-host
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/${DATABASE_NAME:postgres}
     - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME:postgres}
     - SPRING_DATASOURCE_PASSWORD==${DATABASE_PASSWORD:password}
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:password}
      - POSTGRES_USER=${DATABASE_USERNAME:postgres}
      - POSTGRES_DB=${DATABASE_NAME:postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5