version: "3.9"
services:
  web:
    restart: always
    build: .
    container_name: give-host
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    env_file:
      - app.env
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - isolated_nw
  PostgreSQL:
    image: postgres:alpine
    env_file:
      - db.env
    volumes:
      - /root/dockvolumes/database-data:/var/lib/postgresql/data/
    networks:
      - isolated_nw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  isolated_nw:
    driver: bridge