version: "3.9"
services:
  mysqldb:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password
  give-host:
    depends_on:
      - mysqldb
    restart: on-failure
    image: kalpak44/give-host:latest
    container_name: give-host
    ports:
      - "8080:8080"
    environment:
      PAYMENTS_STRIPE_KEY_PUBLIC: ${PAYMENTS_STRIPE_KEY_PUBLIC}
      PAYMENTS_STRIPE_KEY_SECRET: ${PAYMENTS_STRIPE_KEY_SECRET}
volumes:
  db_data: {}